# Generated by Django 4.2.7 on 2023-12-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
